In [6]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b
f=np.dot(a,b)
a_transpose=a.T
print("addition")
print(c)
print("subtraction")
print(d)
print("elemet wise multiplication")
print(e)
print("matrix multiplication")
print(f)
print("transpose")
print(a_transpose)


addition
[[ 6  8]
 [10 12]]
subtraction
[[-4 -4]
 [-4 -4]]
elemet wise multiplication
[[ 5 12]
 [21 32]]
matrix multiplication
[[19 22]
 [43 50]]
transpose
[[1 3]
 [2 4]]


In [11]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]),VT[:n_components, :]))
print("orginal matrix")
print(X)
print("reconstructed")
print(X_reconstructed )



orginal matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reconstructed
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
